config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  post '/' => 'home#answer'

  resources :cards

end

app/models/card.rb
class Card < ActiveRecord::Base
  validates :original_text, :translated_text, :review_date, presence: true
  validate :check_cards

  before_create do
    self.review_date = DateTime.now.next_day(3)
  end

  def check_cards
    if original_text.casecmp(translated_text) == 0
      errors.add(:translated_text, "can't be the same as original text")
      errors.add(:original_text, "can't be the same as translated text")             
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :find_card,
      :only => [:show, :update, :edit, :destroy]

  def index
    @cards = Card.all
  end

  def create
    @card = Card.new(card_params)
    if @card.save
      redirect_to @card
    else
      render "new"
    end
  end

  def update
    if @card.update(card_params)
      redirect_to @card
    else
      render "edit"
    end
  end

  def show
  end

  def new
    @card = Card.new
  end

  def edit
  end

  def destroy
    @card.destroy
    redirect_to cards_path
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text)
    end

    def find_card
      @card = Card.find(params[:id])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @card = Card.first
  end

  def answer

    @answer = params[:answer]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for @card do |f| %>
  <%= f.input :original_text, label: "Original text", input_html: { class: 'form-control' }%>
  <%= f.input :translated_text, label: "Translated text", input_html: { class: 'form-control' }%>
  <%= f.button :submit %>
<% end %>

app/views/cards/edit.html.erb
<div class="col-xs-6">
  <h1>Edit card <%= @card.id %></h1>
  <%= render partial: "form" %>
</div>

app/views/cards/index.html.erb
<div class="jumbotron">
  <h1>All cards</h1>
</div>
<table class="table table-striped">
  <tr>
    <th>#</th>
    <th>Original text</th>
    <th>Translated text</th>
    <th>Review date</th>
    <th>Actions</th>
  </tr>
  <% @cards.each do |card| %>
    <tr>
      <td><%= card.id %></td>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= l card.review_date, format: :short  %></td>
      <td><%= link_to 'Просмотреть', card_path(card.id) %>/ <%= link_to 'Редактировать' , edit_card_path(card.id) %>/
              <%= link_to 'Удалить' , card_path(card), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/cards/new.html.erb
<div class="col-xs-6">
  <h1>Create new card</h1>
  <%= render partial: "form" %>
</div>

app/views/cards/show.html.erb
<h1>Card # <%= @card.id %></h1>
<div class="col-xs-4">
<table class="table table-striped">
  <tr>
    <th>Original text</th>
    <td><%= @card.original_text %>
  </tr>
  <tr>
    <th>Translated text</th>
    <td><%= @card.translated_text %>

  </tr>
  <tr>
    <th>Review date</th>
    <td><%= l @card.review_date, format: :short%></td>
  </tr>
</table>
<%= link_to 'Назад к списку карточек', cards_path %>
</div>

app/views/home/answer.html.erb
<h1>Вы ответили:</h1>
<h3><%= @answer %></h3>
<%= link_to 'К следующей карточке', controller: 'home' %>

app/views/home/index.html.erb
<p class="lead">
  Проверь себя
</p>
<h3>Слово: <%= @card.original_text %></h3>
<%= form_tag("/", method: "post") do %>
  <%= label_tag(:answer, "Перевод:") %>
  <%= text_field_tag(:answer) %>
  <%= submit_tag("Ответить") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<body>
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">Flashcards</a>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Все карточки', controller: 'cards' %></a></li>
        <li><%= link_to 'Добавить карточку', new_card_path %></a></li>
      </ul>
    </div>
  </nav>

  <div class="container-fluid">
    <%= yield %>
  </div>
</body>
</html>